/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.0/userguide/tutorial_java_projects.html
 */

plugins {

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    maven("https://jitpack.io");
}

dependencies {
    implementation("com.github.Project2100:java-commons:master-SNAPSHOT");
}

application {

    // Define the main class for the application.
    mainClassName = "chronos.Main"
}

tasks.withType(JavaCompile::class){

    // Using some special characters in Ananke.java
    options.encoding = "UTF-8"

    // For thorough compile-time output
    options.compilerArgs.add("-Xlint:unchecked")
    options.compilerArgs.add("-Xlint:deprecation")
}
